---
- name: Toggle Proxmox Backup Server enterprise repository
  hosts: all

  vars:
    enterprise_enabled: false

  tasks:
    - name: 'Check PBS repository file'
      ansible.builtin.stat:
        path: /etc/apt/sources.list.d/pbs-enterprise.list
      register: pbs

    - name: '{% if enterprise_enabled %}Enable{% else %}Disable{% endif %} PBS enterprise repository'
      when: pbs.stat.exists
      ansible.builtin.replace:
        path: /etc/apt/sources.list.d/pbs-enterprise.list
        regexp: "{% if enterprise_enabled %}'^# deb'{% else %}'^deb'{% endif %}"
        replace: "{% if enterprise_enabled %}'deb'{% else %}'# deb'{% endif %}"
