---
- name: Register a file as a Swarm secret
  hosts: all

  vars:
    file_path: "/tmp/cluster_file"
    secret_name: "cluster_file"

  tasks:
    - name: "Register the secret '{{ secret_name }}'"
      community.docker.docker_secret:
        name: "{{ secret_name }}"
        data_src: "{{ file_path }}"
        state: "present"
