---
- name: Register a random password as a Swarm secret
  hosts: all

  vars:
    password_length: 64
    secret_name: "cluster_password"

  tasks:
    - name: "Generate a random password"
      ansible.builtin.shell: "LC_ALL=C tr -dc '[:graph:]' < /dev/urandom | head -c {{ password_length }}"
      changed_when: true
      register: cluster_password

    - name: "Register the secret '{{ secret_name }}'"
      community.docker.docker_secret:
        name: "{{ secret_name }}"
        data: "{{ cluster_password.stdout }}"
        state: "present"
