---
- name: Install Traefik
  hosts: all

  vars:
    acme_email: 'noreply@example.org'
    enable_https_redirect: true
    image_tag: 'latest'
    dns_provider: ''
    le_aws_acces_key_id: ''
    le_aws_access_key_secret: ''
    le_cloudflare_api_email: ''
    le_cloudflare_api_key: ''
    le_cloudflare_dns_api_token: ''
    le_cloudflare_zone_api_token: ''
    le_digitalocean_auth_token: ''
    le_dreamhost_api_key: ''
    le_lightsail_dns_zone: ''
    le_ovh_application_key: ''
    le_ovh_application_secret: ''
    le_ovh_consumer_key: ''
    le_ovh_endpoint: ''
    le_route53_aws_region: ''
    le_route53_hosted_zone_id: ''
    timezone: 'America/Sao_Paulo'

  tasks:
    - name: 'Pull the latest Traefik image'
      community.docker.docker_image:
        name: 'docker.io/traefik:{{ image_tag }}'
        source: 'pull'

    - name: 'Check the current service'
      community.docker.docker_swarm_service_info:
        name: 'proxy_traefik'
      register: check_proxy_traefik

    - name: 'Remove service if exists'
      when: check_proxy_traefik.exists
      community.docker.docker_swarm_service:
        name: 'proxy_traefik'
        state: 'absent'

    - name: 'Initialize the service'
      community.docker.docker_swarm_service:
        name: 'proxy_traefik'
        image: 'docker.io/traefik:{{ image_tag }}'
        args:
          - '--providers.docker'
          - '--providers.docker.exposedbydefault=false'
          - '--providers.docker.swarmmode'
          - '--entrypoints.http=true'
          - '--entrypoints.http.address=:80'
          - '{% if enable_https_redirect %}--entrypoints.http.http.redirections.entrypoint.to=https{% endif %}'
          - '{% if enable_https_redirect %}--entrypoints.http.http.redirections.entrypoint.scheme=https{% endif %}'
          - '--entrypoints.https=true'
          - '--entrypoints.https.address=:443'
          - '--certificatesResolvers.letsencrypt.acme.email={{ acme_email }}'
          - '--certificatesResolvers.letsencrypt.acme.storage=/etc/traefik/acme.json'
          - '--certificatesresolvers.letsencrypt.acme.dnschallenge={% if dns_provider %}true{% else %}false{% endif %}'
          - '--certificatesresolvers.letsencrypt.acme.{% if dns_provider %}dnschallenge.provider={{ dns_provider }}{% else %}httpChallenge.entryPoint=http{% endif %}'
          - '--accesslog'
          - '--log'
          - '--api'
        env:
          AWS_ACCESS_KEY_ID: '{{ le_aws_acces_key_id }}'
          AWS_HOSTED_ZONE_ID: '{{ le_route53_hosted_zone_id }}'
          AWS_REGION: '{{ le_route53_aws_region }}'
          AWS_SECRET_ACCESS_KEY: '{{ le_aws_access_key_secret }}'
          CF_API_EMAIL: '{{ le_cloudflare_api_email }}'
          CF_API_KEY: '{{ le_cloudflare_api_key }}'
          CF_DNS_API_TOKEN: '{{ le_cloudflare_dns_api_token }}'
          CF_ZONE_API_TOKEN: '{{ le_cloudflare_zone_api_token }}'
          DO_AUTH_TOKEN: '{{ le_digitalocean_auth_token }}'
          DNS_ZONE: '{{ le_lightsail_dns_zone }}'
          DREAMHOST_API_KEY: '{{ le_dreamhost_api_key }}'
          OVH_APPLICATION_KEY: '{{ le_ovh_application_key }}'
          OVH_APPLICATION_SECRET: '{{ le_ovh_application_secret }}'
          OVH_CONSUMER_KEY: '{{ le_ovh_consumer_key }}'
          OVH_ENDPOINT: '{{ le_ovh_endpoint }}'
          TZ: '{{ timezone }}'
        mounts:
          - source: '/var/run/docker.sock'
            target: '/var/run/docker.sock'
          - source: 'proxy_traefik_config'
            target: '/etc/traefik'
            type: 'volume'
        publish:
          - mode: 'host'
            protocol: 'tcp'
            published_port: 80
            target_port: 80
          - mode: 'host'
            protocol: 'tcp'
            published_port: 443
            target_port: 443
        networks:
          - 'public'
        placement:
          constraints:
            - 'node.labels.service-proxy == true'
            - 'node.role == manager'
        mode: 'global'
